name: Metadata yaml file data extractor
runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r ./utilitiesRepository/.github/scripts/api_generator/metadata/requirements.txt
    - name: Check metadata yaml file schema
      shell: bash
      run: |
        python ../utilitiesRepository/.github/scripts/api_generator/metadata/verify_metadata.py \
          --metadata ./apiRepository/spec/metadata.yml \ 
          --schema ./utilitiesRepository/.github/scripts/api_generator/metadata/schema.yml