name: Verify
on:
  workflow_call:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.repository.full_name }}  # Checkout the repository of the caller
          ref: ${{ github.sha }}  # Checkout the commit hash or branch name passed from the caller
      - name: print
        shell: bash
        run: echo $(pwd)
      - name: Verify existance of spec folder
        shell: bash
        run: |
          echo ${{ inputs.apiRepositoryPath }}
          if [ -d "./spec" ]; then
            echo "Directory ${{ inputs.apiRepositoryPath }} exists."
          else
            echo "Directory ${{ inputs.apiRepositoryPath }} does not exist."
            exit 1
          fi