name: Verify
on:
  workflow_call:
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Info
        shell: bash
        run: |
          echo "Executing API verification workflow for:"
          echo "Repository: ${{ github.event.repository.full_name }}"
          echo "Commit: ${{ github.sha }}"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.repository.full_name }}
          ref: ${{ github.sha }}
      - name: Verify existence of metadata yaml spec
        shell: bash
        run: |
          if [ -e "./spec/metadata.yml" ]; then
            echo "Metadata yaml file exists."
          else
            echo "Metadata yaml file does not exist."
            exit 1
          fi
      - name: Verify metadata yaml file
        uses: SielCode/github-utilities/.github/actions/verify_metadata